tap 'common-fate/granted'
tap 'hashicorp/tap'

# Shell
brew 'asdf'
brew 'bash'
brew 'starship'
brew 'stow'

# Neovim
brew 'nvim'
brew 'fd'
brew 'fzf'
brew 'ripgrep'
brew 'tree-sitter'
brew 'tree-sitter-cli'

# Tools
brew 'awscli'
brew 'duckdb'
brew 'go'
brew 'goose'
brew 'gopls'
brew 'granted'
brew 'hashicorp/tap/packer'
brew 'hashicorp/tap/terraform'
brew 'hashicorp/tap/terraform-ls'
brew 'helm'
brew 'jq'
brew 'lua-language-server'
brew 'luarocks'
brew 'opencode'
brew 'sqlc'
brew 'tealdeer'
brew 'terragrunt'
brew 'yq'
brew 'zoxide'
brew 'dotnet'

# Libraries
brew 'libyaml' # ruby-lsp dependency

# Casks
cask 'flutter'
cask 'font-jetbrains-mono-nerd-font'
cask 'ghostty'
