alias tfi='terraform init'
alias tfim='terraform import'
alias tfp='terraform plan'
alias tfpp='terraform plan -out=plan.tfplan'
alias tfa='terraform apply'
alias tfap='terraform apply plan.tfplan'
alias tfd='terraform destroy'
alias tfss='terraform state show'
