vim.keymap.set('i', 'jj', '<Esc>', { noremap = true, silent = true })
vim.keymap.set({ 'n', 'v' }, '<C-a>', '^', { noremap = true, silent = true })
vim.keymap.set('i', '<C-a>', '<C-o>^', { noremap = true, silent = true })
vim.keymap.set({ 'n', 'v' }, '<C-e>', '$', { noremap = true, silent = true })
vim.keymap.set('i', '<C-e>', '<C-o>$', { noremap = true, silent = true })
vim.keymap.set('t', '<Esc>', '<C-\\><C-n>', { noremap = true, silent = true })
vim.keymap.set('t', 'jj', '<C-\\><C-n>', { noremap = true, silent = true })
